stages:
  - update
  - build
  - check

job:on-schedule:
  stage: check
  only:
    - schedules
  image: $CI_REGISTRY_IMAGE
  before_script:
    - ls -lisa
    - ./.gitlab/before_script.sh
  script:
    - ./.gitlab/script.sh

update_repo:
  stage: update
  only:
    - web
  script:
    - ./.gitlab/update_repo.sh

build_docker:
  stage: build
  only:
    - web
  tags:
    - docker-image-build
  script: "echo 'Building docker image..." # unused but this line is required by GitLab CI
  variables:
    TO: $CI_REGISTRY_IMAGE # $CI_REGISTRY_IMAGE is the registry space for this particular repository
    # TO can be omitted and the imaged will be push to $CI_REGISTRY_IMAGE:latest
